#
# Jekyll configuration
#
#destination: ./_site
auto:        false
lsi:         true # better related posts
server_port: 4000
pygments:    false
markdown:    maruku
permalink:   none
maruku:
  use_tex:    false
  use_divs:   false
  png_dir:    images/latex
  png_url:    /images/latex

#
# Site configuration
#
url:          http://localhost:4000
title:        Test Load Balancer(TLB)
description:  A tool that allows load-balancing/parallelizing your test across multiple machines, to bring project build time down.
keywords:     tlb, test-load-balancer, ant, buildr, java, junit, rspec, test::unit, ruby, .Net, Nant, NUnit, Twist, tlb_rb
author:       Janmejay Singh
email:        singh.janmejay@gmail.com
analytics_id: UA-10148132-2
